version: "3"

services:
  jenkins-docker:
    image: docker:dind
    privileged:
      true
    environment:
      - DOCKER_TLS_CERTDIR=/certs
    volumes:
      - jenkins-docker-certs:/certs/client
      - jenkins-data:/var/jenkins_home
    ports:
      - 2377:2376
    #storage-driver:
    #  - overlay2

  jenkins-built-in:
    # image: jenkins/jenkins:lts
    # image: jenkins/jenkins:2.492.3-jdk17
    build: ./built-in
    container_name: jenkins_sandbox
    privileged: true
    user: root
    ports:
      - 8081:8080
      - 50001:50000
    volumes:
      #- ${JENKINS_HOME_PATH}:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - jenkins-data:/var/jenkins_home
      - jenkins-docker-certs:/certs/client:ro

  jenkins-agent:
    #image: jenkins/ssh-agent:jdk11
    build:
      context: ./ssh-agent-android
    container_name: jenkins_agent
    privileged: true
    user: root
    expose:
      - 22
    ports:
      - "2201:22"
    environment:
      - JENKINS_AGENT_SSH_PUBKEY=${JENKINS_AGENT_SSH_PUBLIC_KEY}
    secrets:
      - ssh_agent_pubkey

  jenkins-agent-android:
    #image: jenkins/ssh-agent:jdk11
    build:
      context: ./ssh-agent-android
      #args:
      #  USER_NAME: ${USER}
      #  GROUP_NAME: ${USER}
      #  USER_ID: $(id -u ${USER})
      #  # Option g is ambiguous (gecos, gid, group)
      #  #GROUP_ID: $(id --group ${USER})
      #  GROUP_ID: 11000

    container_name: jenkins_agent_android
    privileged: true
    user: root
    expose:
      - 22
    ports:
      - "2221:22"
    environment:
      - JENKINS_AGENT_SSH_PUBKEY=${JENKINS_AGENT_SSH_PUBLIC_KEY}
    secrets:
      - ssh_agent_pubkey
 
  git-server-jkarlos:
    image: jkarlos/git-server-docker
    # build: .
    restart: always

    container_name: git_server_jkarlos

    ports:
      - "2220:22"

    volumes:
      - ~/git-server/keys:/git-server/keys
      - ~/git-server/repos:/git-server/repos

  git-server-ubivisgmbh:
    image: ubivisgmbh/git-server:latest
    container_name: git_server_ubivisgmbh
    restart: always
    ports:
      - 2022:22
    environment:
      #- GIT_USER_PASSWORD=[secret]
      #- "GIT_AUTHORIZED_KEYS=[ssh-rsa xxxxx xxx@xxx]\n[ssh-rsa xxxxx xxx@xxx]"
      - GIT_HOST_HINT=example.org:2022
    volumes:
      #- config:/etc/git
      #- data:/srv/git
      - ../../../CI_CD/gitserver:/srv/git

  git-server-rockstorm:
    container_name: git_server_rockstorm

    image: rockstorm/git-server

    environment:
      #GIT_PASSWORD_FILE: /run/secrets/git_password
      SSH_AUTH_METHODS: "publickey"
      #SSH_HOST_KEYS_PATH: /tmp/host-keys
      #REPOSITORIES_HOME_LINK: /srv/git/project
    ports:
      - 2202:22

    volumes:
      #- /path/to/password/file:/run/secrets/git_password:ro
      #- /path/to/authorized_keys:/home/git/.ssh/authorized_keys
      - ./ssh-agent/.ssh/id_rsa.pub:/home/git/.ssh/authorized_keys
      #- ~/.ssh/id_rsa.pub:/home/git/.ssh/authorized_keys
      # - examples/sshd_config:/etc/ssh/sshd_config:ro
      # - /path/to/host-keys:/tmp/host-keys:ro
      - ../../../CI_CD/gitserver:/srv/git

  gitweb:
    image: rockstorm/gitweb

    volumes:
      - ../../../CI_CD/gitserver:/srv/git:ro
volumes:
  jenkins-data:
  jenkins-docker-certs:

secrets:
   ssh_agent_pubkey:
     file: ./ssh-agent/.ssh/id_rsa.pub