node('linux'){
  git url: 'https://github.com/jglick/simple-maven-project-with-tests.git'
  echo "linux"
  //def mvnHome = tool 'M3'
  //env.PATH = "${mvnHome}/bin:${env.PATH}"
  //sh 'mvn -B clean verify'
}

node('docker'){
  git url: 'https://github.com/jglick/simple-maven-project-with-tests.git'
  echo "docker"
  def mvnHome = tool 'M3'
  env.PATH = "${mvnHome}/bin:${env.PATH}"
  sh 'mvn -B clean verify'
}

